### ISSUE TITLE
Recommendation: Turn into pip package

### ISSUE THREAD

**Issue by PeterSR** [cphnano/pySpectroWorks#2]
I love the idea of SpectroWorks Python bindings! Can I recommend that it is turned into a proper Python package that can be installed via pip? One could follow this guide: https://packaging.python.org/tutorials/packaging-projects/

I would be happy to create PR for it.

**Comment by ttolbol** [comment]
That's a great idea! I will look into it

**Comment by ttolbol** [comment]
Closed by #5
