### ISSUE TITLE
Investigate and fix session expiration in Binder - returning: "Directory not found" after 5-10 min inactivity

### ISSUE THREAD

**Issue by vino-dk** [cphnano/pySpectroWorks#4]

**Comment by vino-dk** [comment]
Looks like Binder sessions expires after 10min of inactivity. 

From Binder [FAQ](https://mybinder.readthedocs.io/en/latest/faq.html)

> How long will my Binder session last?
> Binder is meant for interactive and ephemeral interactive coding, meaning that it is ideally suited for relatively short sessions. Binder will automatically shut down user sessions that have more than 10 minutes of inactivity (if you leave your window open, this will be counted as “activity”).
> 
> Binder aims to provide at least 12 hours of session time per user session. Beyond that, we cannot guarantee that the session will remain running.

**Comment by ttolbol** [comment]
We've switched to colab
